### ISSUE TITLE
Default mounted volumes contain installed files, cannot swap them for empty named volumes.

### ISSUE THREAD

**Issue by indridieinarsson** [mariadb-corporation/mariadb-community-columnstore-docker#7]
I'm trying to use this container in a simple kubernetes (microk8s) setup, but I don't think my problem is kubernetes-specific.
When wiring up the container into a pod, I need to define 3 persistent volumes and 3 corresponding persistent volume claims, to plug into the 3 defined volumes in the Dockerfile :  `VOLUME ["/etc/columnstore", "/var/lib/columnstore", "/var/lib/mysql"]` 

Looking into the **mariadb-columnstore** package, I see it installs files into the two first ones  (`/etc/columnstore` and `/var/lib/columnstore`). 

Now, when I start the pod, all three folders (`/etc/columnstore`, `/var/lib/columnstore` and `/var/lib/mysql`) are empty, since empty volumes are mounted onto them. Unsurprisingly, the lack of the files that were installed thereprevents the mariadb service from starting up properly.
I'm confident that my setup is good apart from this - using the `_/mariadb:10.5` image instead works like a charm.

I'll bet a beer that I'll get the same behaviour by using vanilla docker to plug empty docker volumes into the 3 "slots", instead of using kubernetes.

I have tried digging around in the **mariadb-columnstore** package, to see whether I can mount an empty volume somewhere deeper in the `/var/lib/columnstore` hierarchy. There seem to folders called `data` and `data1` in there, but I'm not sure where exactly columnstore engine stores the actual database files.

Another approach would be to change the config, so that the columnstore storage files are stored in a folder that doesn't contain files from the installer, so it can safely be empty on start.

Greetings,
Indriði

**Comment by drrtuy** [comment]
The point is that mariadb-columnstore depends on mariadb-server package that uses /var/lib/mysql.
MCS stores the data in dbroots that are directories /var/lib/columnstore/data1, data2...
I don't have experience with k8s so can't answer you how to translate Docker images into k8s images in the scenario when Dockerfile installs packages using persistant volumes.

**Comment by indridieinarsson** [comment]
Thanks for the reply.

> The point is that mariadb-columnstore depends on mariadb-server package that uses /var/lib/mysql.
> MCS stores the data in dbroots that are directories /var/lib/columnstore/data1, data2...

The problem here is that columnstore installs files it depends on in the same folder where data is stored. I think (not the biggest expert on this, so feel free to disagree!) that it is a bit "against the point" of containerisation to have files that executables depend on in a volume, this prevents you from ever swapping out the volume for a fresh one.  Comparing to  /var/lib/mysql I _think_ this folder contains only files generated at runtime, so starting with it empty is ok (equivalent to wiping the DB).

> I don't have experience with k8s so can't answer you how to translate Docker images into k8s images in the scenario when Dockerfile installs packages using persistant volumes.

Regarding this, there is no translation per se, you can use the exact same image. Only difference is that you start off with an empty volume. Main difference is probably, that when declaring a volume in the Dockerfile, docker creates a volume automatically, and populates it with whatever was in the folder at creation time. This docker-volume is not available to kubernetes, so I have to start with an empty one, which breaks things.

Is there a simple way to configure columnstore so that data is stored somewhere else, instead of /var/lib/columnstore/dataX ?

Greetings,
Indriði

**Comment by dhall-MariaDB** [comment]
I know nothing about how to use kubernetes, but this may help.
If you have a system with MariaDB and Columnstore installed, the default directories will be:
/etc/my.cnf.d                                           // configuration files
/etc/columnstore                                    // Columnstore specific configurations
/usr/bin/                                                 // All the binaries
/var/lib/mysql                                         // MariaDB data files
/var/lib/columnstore/                             // Columnstore runtime stuff
/var/lib/columnstore/data                      // Columnstore metadata and bulk insert logs
/var/lib/columnstore/data1                    // dbroot1 table data

You most likely will need root priv to do these things.
If your /var/lib/mysql directory is empty, you can do the following (with database not running). 
In /etc/my.cnf.d/columnstore.cnf
Comment plugin-load-add=ha_columnstore.so
mysql_install_db --user=mysql
Uncomment plugin-load-add=ha_columnstore.so

If your /var/lib/columnstore directory is empty, run (with database not running)
columnstore-post-install

I know there is a way to have your data in a different place than /var/lib/columnstore/data1.
I've not tried this, but here's something that might work.
mcsSetConfig WriteEngine SharedNothingRoot <Your data dir>

If this really messes things up, then
mcsSetConfig -x WriteEngine SharedNothingRoot <Your data dir>
Will reverse the above operation.

You need to restart columnstore any time you change configurations. After restarting columnstore, it's a good idea to restart mariadb after.
To be safe I always shut down mariadb and columnstore, do my changes, then start columnstore, then start mariadb.

Hope this helps

David Hall

**Comment by bruceoutdoors** [comment]
I'm stumped by this as well. I'm sure it's kubernetes specific, since my docker compose version of the code works just fine:

```yaml
services:
  db:
    image: mariadb/columnstore
    expose:
      - 3306:3306
    volumes:
      - "mariadb_mysql_data:/var/lib/mysql"
      - "mariadb_columnstore_data:/var/lib/columnstore"

volumes:
  mariadb_mysql_data:
  mariadb_columnstore_data:
```

Here's the kubernetes equivalent:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  serviceName: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mariadb/columnstore
        imagePullPolicy: IfNotPresent
        name: db
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
          - name: columnstore-data
            mountPath: /var/lib/columnstore
        ports:
          - name: http
            containerPort: 3306
            protocol: TCP
      volumes:
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: columnstore-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
```

...which results in these errors:

```
Starting...
StorageManager PID = 287
loading BRM
cat: /var/lib/columnstore/data1/systemFiles/dbrm/BRM_saves_current: No such file or directory
/var/lib/columnstore/data1/systemFiles/dbrm/BRM_saves_current does not exist.
workernode PID = 301
controllernode PID = 304
PrimProc PID = 308
ExeMgr PID = 363
WriteEngineServer PID = 366
DMLProc PID = 387
DDLProc PID = 390
Starting MariaDB.210915 05:20:35 mysqld_safe Logging to '/var/lib/mysql/db-0.err'.
210915 05:20:36 mysqld_safe Starting mariadbd daemon with databases from /var/lib/mysql
 ERROR! 
/usr/share/mysql/mysql.server: line 264: kill: (405) - No such process
```

And in the specified `/var/lib/mysql/db-0.err`:

```
...
2021-09-15  3:24:22 0 [ERROR] Could not open mysql.plugin table: "Table 'mysql.plugin' doesn't exist". Some plugins may be not loaded
2021-09-15  3:24:22 0 [ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist
2021-09-15  3:24:22 0 [Note] Server socket created on IP: '::'.
2021-09-15  3:24:22 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.db' doesn't exist
2021-0
```

Without the Kubernetes volume mounts, it works just fine. I check the volume contents via ssh - it seems that within a Kubernetes volume it couldn't write out some folders like `systemFiles` mentioned above, and yet able to write others. 

I've swapped out the image with the standard docker image `mariadb`, and it works just fine, so this like likely very specific to `mariadb/columnstore`, and only seems to happen with Kubernetes.
